os:
  - linux
  - osx
compiler:
  - clang
  - gcc
language: cpp
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install build-essential cmake libqt4-dev libgcrypt11-dev zlib1g-dev libxtst-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake qt libgcrypt; fi
before_script: mkdir build && pushd build
script:
  - cmake ..
  - make
  - make test
